@baseurl = http://localhost:3001/api

### Get all persons
GET {{baseurl}}/persons

### Create a new listing
# @name person
POST {{baseurl}}/persons
Content-Type: application/json

{
  "name": "John Doe",
  "number": "1234567890"
}

###
@id = {{person.response.body.$.id}}
###

### Get a specific person by ID
GET {{baseurl}}/persons/{{id}}

### Update a person by ID
PUT {{baseurl}}/persons/{{id}}
Content-Type: application/json

{
  "name": "Farmer John",
  "number": "9876543210"
}

### Delete a person by ID
DELETE {{baseurl}}/persons/{{id}}

### Intentionally fail to get a person by ID
GET {{baseurl}}/persons/1234567890